### ISSUE TITLE
How to get the tensorflow arm dll under linux 

### ISSUE THREAD

**Issue by lingbao00** [dongchangzhang/NewFeelings#1]
in your blog,you say you just get the arm use tensorlfow dll,canyou share with me ,i do not know how to use bazel cross compile for arm.

**Comment by vhdsih** [comment]
Do you need the dynamic link library of tensorflow -- tensorflow.so?
This app can work on arm, x86, x86_64 now, and you can find these 'tensorflow.so' at [there](https://github.com/dongchangzhang/NewFeelings/tree/master/app/src/main/jniLibs).

but when i write this app, the version of tf is 0.12, so if you want a new one, you can visit the github of tensorflow, and you can find 'Android: demo APK, native libs (build history)' in readme, and then you can download the '.so' files.
