### ISSUE TITLE
自己创建的数据集 训练得到的.pb文件无法应用在项目中

### ISSUE THREAD

**Issue by GL1920** [dongchangzhang/NewFeelings#3]
我在百度图片上收集了14种分类，每种类数量不同，最少有50左右，最多有900多张。根据作者你在博客上的步骤进行训练自己的数据集，但最后编译安装项目后相册页空白，没有完成分类过程。
在PC机上使用训练的pb文件能够准确识别，也已经经过处理，减小体积，并在config.java文件中做了如下修改：
`   public static final int NUM_CLASSES = 14;
    public static final int INPUT_SIZE = 299;
    public static final int IMAGE_MEAN = 128;
    public static final float IMAGE_STD = 128;
    public static final String INPUT_NAME = "Mul";
    public static final String OUTPUT_NAME = "final_result:0";
    public static final String MODEL_FILE = "file:///android_asset/lala_graph.pb";
    public static final String LABEL_FILE = "file:///android_asset/llll_labels.txt";

public static String[] album_type_name = {

            "植物","艺术品",
            "合影", "风景","演出",
            "美食", "旅游","室内", "乐器", "自拍", "文字","建筑","聚餐","二次元"

    };

    public static String[] tf_type_name = {

            "zhiwu","art",
            "peoples", "view","show",
            "food", "travel","indoor", "instration", "zipai", "word","establish","eat","er"

    };`
其中我的labels文件如下：
`indoor 
food 
travel 
word 
show 
zipai 
art 
zhiwu 
er 
establish 
peoples 
view 
instration 
eat 
`
之所以是英文，是我之前使用中文分类，tensorflow无法构建.pb文件和labels文件，只有在使用英文字母的时候才可以正常训练。想问一下作者你是如何训练出中文标签的？希望作者看到有时间回复一下，这个问题困扰我好久了，谢谢！

**Comment by GL1920** [comment]
AS中显示的log如下：
`04-25 19:42:52.160 13646-17546/? E/native: executor.cc:390 Executor failed to create kernel. Invalid argument: NodeDef mentions attr 'dilations' not in Op<name=Conv2D; signature=input:T, filter:T -> output:T; attr=T:type,allowed=[DT_HALF, DT_FLOAT, DT_DOUBLE]; attr=strides:list(int); attr=use_cudnn_on_gpu:bool,default=true; attr=padding:string,allowed=["SAME", "VALID"]; attr=data_format:string,default="NHWC",allowed=["NHWC", "NCHW"]>; NodeDef: conv/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_Mul_0, conv/conv2d_params)
                                           	 [[Node: conv/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_Mul_0, conv/conv2d_params)]]
04-25 19:42:52.160 13646-17546/? I/native: tensorflow_inference_jni.cc:228 End computing. Ran in 544ms (493ms avg over 58 runs)
04-25 19:42:52.160 13646-17546/? E/native: tensorflow_inference_jni.cc:233 Error during inference: Invalid argument: NodeDef mentions attr 'dilations' not in Op<name=Conv2D; signature=input:T, filter:T -> output:T; attr=T:type,allowed=[DT_HALF, DT_FLOAT, DT_DOUBLE]; attr=strides:list(int); attr=use_cudnn_on_gpu:bool,default=true; attr=padding:string,allowed=["SAME", "VALID"]; attr=data_format:string,default="NHWC",allowed=["NHWC", "NCHW"]>; NodeDef: conv/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_Mul_0, conv/conv2d_params)
                                           	 [[Node: conv/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_Mul_0, conv/conv2d_params)]]
04-25 19:42:52.160 13646-17546/? E/native: tensorflow_inference_jni.cc:170 Output [final_result:0] not found, aborting!
04-25 19:42:52.160 13646-17546/? E/ZipFileCache: init failed when open zip file.`

**Comment by vhdsih** [comment]
训练和分类过程都是用的英文，在显示的时候对根据英文分类结果到中文的数组中根据索引查找对应的中文类名。

**Comment by GL1920** [comment]
恩恩，那个config.Java是我自己后来改的，我见作者你的labels文件中分类类别就是中文，如下：
`风景
教室
花朵
很多人
人物
汽车
工作地点
雪景
物品
动物
文字
建筑
二次元
`
还有一个问题就是我把模型换成自己训练的，编译安装后相册页是空的，也就是没有实现对图片的分类，是不是还需要改一些地方？

**Comment by vhdsih** [comment]
你没换自己的模型时候可以分类吗，你在as下run里看看log？另外我记得还有一个常量是label的数目，你看看改了吗。
这个项目是我之前刚学android时候写的，逻辑挺乱的，仅供参考。

**Comment by GL1920** [comment]
我没换的时候可以正常分类，常量也改了，如下：
`
    // how many
    public static int imageNumber = 14;

    public static List<String> needToBeClassified;

    public static int tf_type_times = 14;`
看了log好像是参数问题，如下：
`tensorflow_inference_jni.cc:233 Error during inference: Invalid argument: NodeDef mentions attr 'dilations' not in Op<name=Conv2D; signature=input:T, filter:T -> output:T; attr=T:type,allowed=[DT_HALF, DT_FLOAT, DT_DOUBLE]; attr=strides:list(int); attr=use_cudnn_on_gpu:bool,default=true; attr=padding:string,allowed=["SAME", "VALID"]; attr=data_format:string,default="NHWC",allowed=["NHWC", "NCHW"]>; NodeDef: conv/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_Mul_0, conv/conv2d_params)
                                         	 [[Node: conv/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_Mul_0, conv/conv2d_params)]]`
那个dilations出错，我是在cpu上训练的，但好像
`use_cudnn_on_gpu=true,`这些可以在哪改？

**Comment by vhdsih** [comment]
我当时用的tf版本好像是0.12，是不是和你现在用的tf版本有关，或者tf有什么地方改了？对于你的问题我也不知道该怎么改。
如果你想在Android上实现类似功能的话，这有几个步骤你可以尝试：
1. 看看是否能够修改当前的代码
2. 实在不行的话，下载tf0.12试一试
3. 使用最新的tf重新写：
如果你打算尝试这一步，（我更支持你这样做），并且没有头绪，这里有几个偷懒的技巧：
(1)到tf的github下载android最新的动态链接库 [ 放到这个位置 ](https://github.com/dongchangzhang/NewFeelings/tree/master/app/src/main/jniLibs)
(2) 到tf的github中找到它给出的android的例子，筛选出调用接口部分直接放入到你的项目中，
[这里是我筛选的例子](https://github.com/dongchangzhang/NewFeelings/tree/master/app/src/main/java/org/tensorflow)，你可以在你的代码中直接调用相应的接口即可。

**Comment by vhdsih** [comment]
或者你将我的那里面的动态链接库换成最新的，如果app可以正常运行的话，直接用我的那个tensorflow包即可

**Comment by vhdsih** [comment]
你应该也可以直接使用api，https://www.tensorflow.org/versions/master/mobile/

**Comment by GL1920** [comment]
我试了一下第三种方法，使用我安装的tensorflow中的动态链接库和tensorflow包，编译安装后相册页还是空白的，我在pc端使用训练好的模型是可以进行分类的，所以模型应该没问题，然后log没显示错误，不知道是哪错了

**Comment by helloworkcupid** [comment]
我在这里问下，我也想把大数据训练的模型.pb 文件导入类似这样的项目，请问怎么一步步来呢？
