### ISSUE TITLE
请教，如何把训练的模型集成到Android 项目中？

### ISSUE THREAD

**Issue by helloworkcupid** [dongchangzhang/NewFeelings#4]
我看了Tensorflow的介绍，感觉还有些不熟悉，我想下作者您是在windows 环境下集成的Android 项目吗？
我想是实现的 打开摄像头 ，画面出现的物体，会进行一个标注，标明这是什么，，，现在已经有.pb文件 在pc ,ios成功运行了，请问我该如何集成到android 呢？多谢

**Comment by helloworkcupid** [comment]
能不能加下qq?

**Comment by vhdsih** [comment]
训练结束得到的pb文件，放到app/src/main/assets下，在调用tf时修改你的类别数目等相关信息即可。

**Comment by helloworkcupid** [comment]
我想把我的pb 文件和类别信息给你，能不能帮我调下呢？还有你用的什么环境呢，windows ,还是linux?

**Comment by helloworkcupid** [comment]
请问，修改类别数目等相关相信，都是那些些参数，有点蒙蔽

**Comment by vhdsih** [comment]
在我使用的tf0.12版本的时候，项目tf里的配置信息大致包括：
    public static final int NUM_CLASSES = 14;
    public static final int INPUT_SIZE = 299;
    public static final int IMAGE_MEAN = 128;
    public static final float IMAGE_STD = 128;
    public static final String INPUT_NAME = "Mul:0";
    public static final String OUTPUT_NAME = "final_result:0";
    public static final String MODEL_FILE = "file:///android_asset/stripped_graph.pb";
    public static final String LABEL_FILE = "file:///android_asset/retrained_labels.txt";
classes就是类别数目，其他几个信息你需要查一下。
我的项目的这些信息都在 [这个文件中](https://github.com/dongchangzhang/NewFeelings/blob/master/app/src/main/java/com/fghz/album/Config.java)，当然后面还有其他的一些信息要改。
你可以到[tensorflow的android-example](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/android/src/org/tensorflow/demo/ClassifierActivity.java)查看各个变量含义的具体信息。

我写这个程序时tf对android的支持没有现在完善，而且我只是调用了接口。现在tf版本已经更新，不知道相关细节是否有所改变。希望 #3 里面的某些信息能带给你启发。

**Comment by vhdsih** [comment]
最好看看tensorflow官方的Android-Demo

**Comment by helloworkcupid** [comment]
这其中，INPUT_NAME，OUTPUT_NAME 又代表什么呢？和数据组对接的时候，不知道都是什么？

**Comment by helloworkcupid** [comment]
哥们，你好，我用linux的系统跑官方的demo 跑通了，我发现你这个里面没有bazel 进行打包什么的，你这个用官方哪个demo 改的呢？我也想更换成windows 环境下操作，这是地址：https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android，你帮我看看，你能用windows 跑通 吗？谢谢
